# render.yaml - ZeroDay AI Platform Deployment Configuration
services:
  # FastAPI Backend Service
  - type: web
    name: zeroday-backend
    runtime: python
    plan: starter  # Free tier - upgrade to standard for production
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      cd api && uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: DATABASE_URL
        fromDatabase:
          name: zeroday-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: zeroday-redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: ANTHROPIC_API_KEY
        sync: false  # Set this manually in Render dashboard  
      - key: CORS_ORIGINS
        value: "https://zeroday-frontend.onrender.com,http://localhost:3000"
    healthCheckPath: /health
    autoDeploy: true
    region: oregon  # Choose: oregon, frankfurt, singapore
    rootDir: .
    
  # Next.js Frontend Service  
  - type: web
    name: zeroday-frontend
    runtime: node
    plan: starter  # Free tier
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    startCommand: |
      cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: "18.17.0"
      - key: NEXT_PUBLIC_API_URL
        value: "https://zeroday-backend.onrender.com"
      - key: NEXT_PUBLIC_ENVIRONMENT
        value: "production"
    autoDeploy: true
    region: oregon
    rootDir: .

# Database Services
databases:
  - name: zeroday-postgres
    databaseName: zeroday_db
    user: zeroday_user
    plan: starter  # Free tier - 1GB storage
    region: oregon
    
  - name: zeroday-redis
    plan: starter  # Free tier - 25MB memory
    region: oregon

# Environment Groups (shared across services)
envVarGroups:
  - name: zeroday-shared
    envVars:
      - key: APP_NAME
        value: "ZeroDay AI Platform"
      - key: VERSION
        value: "1.0.0"
      - key: LOG_LEVEL
        value: "INFO"
      - key: TIMEZONE
        value: "UTC"